### PR TITLE
Fix test assessment json.

### LINKED ISSUE #6: Fix/replace broken test
# 🐛 Bug Report

The `test_assessment()` test in [test_assessment_json.py](https://github.com/cisagov/gophish-tools/blob/develop/tests/test_assessment_json.py) is currently failing.  I commented it out for now, but it needs to be fixed or rewritten so that it passes.

## To Reproduce

- Uncomment the `test_assessment()` test.
- Run `pytest` from the root directory of this repository.

## Expected behavior

The test should pass.

### PR DESCRIPTION
**Pull request by bjb28**
# 

## 🗣 Description
This PR is focused on fixing the `test_assessment()` test in `test_assessment_json.py` so that it passes with a valid response. The specific commits address the following:

- Patch `docopt` to get the initial test to run. 36089bc
- Mock `open` to prevent the test form looking for the files. 536ce8d
- Mock `json.load` to load what would have been read from a file. 536ce8d
- Change to using `csv.DictReader` and mock to provide email csv data. 536ce8d, e001e8a, and 4fd96c1
- Housekeeping within the group build process inside `build.py`. 4fd96c1

Note: I did not address formatting throughout the `builder.py` script with this PR as a future PR will be done for the entire project to address overall formatting in chunks.

## 💭 Motivation and Context
Fixing the `test_assessment()` test will allow for testing of the `builder.py` script. With this test functioning, making future changes to the script will be easier to test. This PR closes #6.

## 🧪 Testing

After getting the pytest to run successfully, I was able to run the automated tests. In addition to this, I also ran several manual tests through the script to ensure a successful run outputs the expected json file.  Failing tests were also run with specific errors to ensure they would successfully produce the expected reaction. 

## 🚥 Types of Changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [x] Breaking change (causes existing functionality to change)

## ✅ Checklist

- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have read the **CONTRIBUTING** document.
- [x] I have added tests to cover my changes.
- [x] All new and existing tests passed.

### CODE REVIEW

**Comment by bjb28** [comment]
@dav3r, if you have not started reviewing this please hold off. I have been working to update the `builder.py` script and would like to incorporate these changes into that update. My goal is to have this completed today or tomorrow.

**Comment by dav3r** [comment]
> @dav3r, if you have not started reviewing this please hold off. I have been working to update the `builder.py` script and would like to incorporate these changes into that update. My goal is to have this completed today or tomorrow.

@bjb28, I started reviewing this last week, but I didn't get too far.  I will wait until I hear from you and then will review the whole thing.

**Comment by bjb28** [comment]
Recommend this PR be closed as PR #14 far exceeds the improvements offered here.

**Comment by dav3r** [comment]
This PR has been replaced by #14.

**Pull request closed without merging**
